server:
  port: 8080
spring:
  data:
    mongodb:
      URI: mongodb://localhost:27017/test_proyecto_banco
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  health:
    circuit-breakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

#resilience4j:
#  circuit breaker:
#    instances:
#      operation:
#        registerHealthIndicator: true
#        eventConsumerBufferSize: 10
#        slidingWindowType: COUNT_BASED
#        slidingWindowSize: 5
#        failureRateThreshold: 5
#        waitDurationInOpenState: 5s
#        permittedNumberOfCallsInHalfOpenState: 3
#        automaticTransitionFromOpenToHalfOpenEnabled: true
